CREATE SEQUENCE  "HR"."DEMO"  MINVALUE 1 
MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

select demo.nextval from dual;

  CREATE TABLE "HR"."EMPLEADOS" 
   (	"ID_EMPLEADO" NUMBER(4,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"APELLIDOS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"SALARIO" NUMBER(7,2) DEFAULT 1080.00 NOT NULL ENABLE, 
	"ACTIVO" CHAR(1 BYTE) DEFAULT 'V', 
	"FINICIO" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"FFIN" DATE, 
	"ID_DEPARTAMENTO" NUMBER(4,0) NOT NULL ENABLE, 
	"EMPLEADO" VARCHAR2(151 BYTE) GENERATED ALWAYS AS ("NOMBRE"||' '||"APELLIDOS") VIRTUAL , 
	 CONSTRAINT "EMPLEADOS_PK" PRIMARY KEY ("ID_EMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "EMPLEADOS_UK_NOMBRE_APELLIDOS" UNIQUE ("NOMBRE", "APELLIDOS")
  USING INDEX (CREATE UNIQUE INDEX "HR"."EMPLEADOS_UK1" ON "HR"."EMPLEADOS" ("NOMBRE", "APELLIDOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" )  ENABLE, 
	 CONSTRAINT "EMPLEADOS_CHK_NOMBRE_CORTO" CHECK (LENGTH(nombre) > 1) ENABLE, 
	 CONSTRAINT "EMPLEADOS_CHK_ACTIVO" CHECK (activo is null or activo in ('V', 'F')) ENABLE, 
	 CONSTRAINT "EMPLEADOS_CHK_FECHAS" CHECK (FFIN IS NULL OR FINICIO <=  FFIN) ENABLE, 
	 CONSTRAINT "EMPLEADOS_FK_DEPARTAMENTO" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "HR"."DEPARTMENTS" ("DEPARTMENT_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HR"."EMPLEADOS"."ACTIVO" IS '
';
   COMMENT ON COLUMN "HR"."EMPLEADOS"."FINICIO" IS '
';
   COMMENT ON TABLE "HR"."EMPLEADOS"  IS 'Demo del curso';

  CREATE INDEX "HR"."EMPLEADOS_INDEX_FECHAS" ON "HR"."EMPLEADOS" ("FINICIO" DESC, "FFIN" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "HR"."JEFES" ("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID") AS 
  SELECT DISTINCT m."EMPLOYEE_ID",m."FIRST_NAME",m."LAST_NAME",m."EMAIL",m."PHONE_NUMBER",m."HIRE_DATE",m."JOB_ID",m."SALARY",m."COMMISSION_PCT",m."MANAGER_ID",m."DEPARTMENT_ID"
FROM hr.employees w JOIN hr.employees m ON w.manager_id = m.employee_id;

select * from jefes where jefes.department_id = '90';
select * from EMP_DETAILS_VIEW;
select * from emp;

select last_name || ', ' || first_name from employees order by 1;
select distinct last_name from employees order by 1;
